version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - '8080:8000'
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    env_file:
      - .env
    networks:
      - mysql-net
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

networks:
  mysql-net:
    driver:  bridge

volumes:
  my-db: