version: '3.3'

services:
  app:
    build: ./Dockerfile
    context: .
    container_name: api
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: db-mysql
    restart: always
    environment:
      MYSQL_DATABASE: ''
      MYSQL_USER: ''
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db: