FROM golang:1.18-alpine AS builder

LABEL maintainer="matheus alencar"

RUN apk update && apk add --no-cache git


WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build cmd/server/main.go

FROM alpine:3.13
WORKDIR /app
COPY --from=builder /app/main .
COPY .env .
COPY application_default_credentials.json .

EXPOSE 8080

CMD ["/app/main"]