version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: sh -c '/app/wait-for.sh db:3306 -t 60 -- /app/main'
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d/

volumes:
  my-db: